"""
This module contains a Caribou migration.

Migration Name: 001_create_table
Migration Version: 20250404071412
"""

def upgrade(connection):
    sql = """
    CREATE TABLE IF NOT EXISTS OPERADORAS (
    REG_ANS INT NOT NULL PRIMARY KEY,
    CNPJ VARCHAR(15) NOT NULL,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    NOME_FANTASIA VARCHAR(255),
    MODALIDADE VARCHAR(100) NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    UF CHAR(3) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    DDD VARCHAR(3),
    TELEFONE VARCHAR(20),
    FAX VARCHAR(15),
    EMAIL VARCHAR(255),
    REPRESENTANTE VARCHAR(255) NOT NULL,
    CARGO_REPRESENTANTE VARCHAR(255) NOT NULL,
    REGIAO_COMERCIAL INT,
    DATA_REGISTRO_ANS DATE NOT NULL
    )
    """    
    
    connection.execute(sql)

def downgrade(connection):
    sql = "DROP TABLE OPERADORAS"
    